"""Directive engine — the component that replaces human meta-cognition.

It reads the situation report plus the mental construct (PRIORITIES, SELF, MACRO_PLAN) and
produces a directive: a structured statement of what this session is for and why. The macro
layer decomposes the directive into concrete tasks.

The directive is also rendered into DIRECTIVE.md so the operator can inspect the agent's
current intent in the workspace editor.
"""

from __future__ import annotations

import json
from typing import Any

from littleman.llm.complete import complete_json
from littleman.llm.client import load_soul
from littleman.llm.prompts import DIRECTIVE_SYSTEM, DIRECTIVE_USER
from littleman.meta import construct


def _soul_excerpt(max_chars: int = 4000) -> str:
    soul = load_soul()
    # The operating principles live near the top of SOUL.md; an excerpt keeps token cost down.
    return soul[:max_chars]


def _render_directive_md(directive: dict[str, Any]) -> str:
    lines = [
        "<!-- Generated by the directive engine at session start. Agent-owned. -->",
        f"# Directive — {directive.get('session_type', 'UNKNOWN')}",
        "",
        f"**Primary focus:** {directive.get('primary_focus', '')}",
    ]
    if directive.get("secondary_focus"):
        lines.append(f"**Secondary focus:** {directive['secondary_focus']}")
    lines += ["", f"**Financial context:** {directive.get('financial_context', '')}", ""]
    if directive.get("opportunity_notes"):
        lines.append("## Opportunities")
        lines += [f"- {n}" for n in directive["opportunity_notes"]]
        lines.append("")
    if directive.get("constraint_notes"):
        lines.append("## Constraints")
        lines += [f"- {n}" for n in directive["constraint_notes"]]
        lines.append("")
    if directive.get("explicit_skip"):
        lines.append("## Explicitly skipped this session")
        lines += [f"- {n}" for n in directive["explicit_skip"]]
        lines.append("")
    return "\n".join(lines)


async def generate(situation_report: dict[str, Any]) -> dict[str, Any]:
    mc = construct.load()
    construct_block = mc.as_prompt_block(
        include=("PRIORITIES.md", "MACRO_PLAN.md", "SELF.md")
    )

    user = DIRECTIVE_USER.format(
        situation_report_json=json.dumps(situation_report, indent=2),
        soul_excerpt=_soul_excerpt(),
    )
    if construct_block:
        user = f"Mental construct (your current cognitive state):\n{construct_block}\n\n{user}"

    directive = await complete_json(DIRECTIVE_SYSTEM, user, tier="primary")

    # Persist the directive into the construct for inspectability.
    construct.write_doc("DIRECTIVE.md", _render_directive_md(directive))

    return directive
